// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform() {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBfTWVYaN-l9Kk28f4JrqRwqxtKroye57U",
    authDomain: "musicapp-8efa0.firebaseapp.com",
    projectId: "musicapp-8efa0",
    storageBucket: "musicapp-8efa0.appspot.com",
    messagingSenderId: "939418840105",
    appId: "1:939418840105:android:0b733c94d9df25738a0038",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTWVYaN-l9Kk28f4JrqRwqxtKroye57U',
    appId: '1:939418840105:android:0b733c94d9df25738a0038',
    messagingSenderId: '939418840105',
    projectId: 'musicapp-8efa0',
    storageBucket: 'musicapp-8efa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfTWVYaN-l9Kk28f4JrqRwqxtKroye57U',
    appId: '1:939418840105:android:0b733c94d9df25738a0038',
    messagingSenderId: '939418840105',
    projectId: 'musicapp-8efa0',
    storageBucket: 'musicapp-8efa0.appspot.com',
    iosBundleId: 'com.example.music_app',
  );
}
